-- PostgreSQL formatted ICD-10 data
CREATE TABLE IF NOT EXISTS icds (
  code varchar(255) PRIMARY KEY,
  name_en text NOT NULL,
  name_id text NOT NULL
);

INSERT INTO icds (code, name_en, name_id) VALUES
('A00.0', 'Cholera due to Vibrio cholerae 01, biovar cholerae', 'Kolera disebabkan Vibrio cholerae 01, biovar cholerae '),
('A00.1', 'Cholera due to Vibrio cholerae 01, biovar eltor', 'Kolera disebabkan Vibrio cholerae 01, biovar eltor '),
('A00.9', 'Cholera, unspecified', 'Kolera, yang tidak spesifik'),
('A01.0', 'Typhoid fever', 'Demam tifoid '),
('A01.1', 'Paratyphoid fever A', 'Demam paratifoid '),
('A01.2', 'Paratyphoid fever B', 'Demam Paratifoid Tipe B '),
('A01.3', 'Paratyphoid fever C', 'Demam Paratifoid Tipe C '),
('A01.4', 'Paratyphoid fever, unspecified', 'Demam paratifoid, tidak spesifik '),
('A02.0', 'Salmonella enteritis', 'Salmonella enteritis '),
('A02.1', 'Salmonella septicaemia', 'Salmonella septicemia '),
('A02.2', 'Localized salmonella infections', 'Infeksi salmonella pada tempat tertentu '),
('A02.8', 'Other specified salmonella infections', 'Infeksi salmonella tertentu lainnya '),
('A02.9', 'Salmonella infection, unspecified', 'Infeksi Salmonella, tidak spesifik '),
('A03.0', 'Shigellosis due to Shigella dysenteriae', 'Shigellosis oleh Disentri Shigella'),
('A03.1', 'Shigellosis due to Shigella flexneri', 'Shigellosis oleh Flexneri Shigella'),
('A03.2', 'Shigellosis due to Shigella boydii', 'Shigellosis oleh Boydii Shigella'),
('A03.3', 'Shigellosis due to Shigella sonnei', 'Shigellosis oleh Sonnei Shigella'),
('A03.8', 'Other shigellosis', 'Shigellosis lainnya '),
('A03.9', 'Shigellosis, unspecified', 'Shigellosis, tidak spesifik '),
('A04.0', 'Enteropathogenic Escherichia coli infection', 'Infeksi Escherichia coli enteropathogenic '),
('A04.1', 'Enterotoxigenic Escherichia coli infection', 'Infeksi Escherichia coli enterotoksigenik '),
('A04.2', 'Enteroinvasive Escherichia coli infection', 'Infeksi Escherichia coli enteroinvasif '),
('A04.3', 'Enterohaemorrhagic Escherichia coli infection', 'Infeksi usus oleh Escherichia coli'),
('A04.4', 'Other intestinal Escherichia coli infections', 'Infeksi usus Escherichia coli lainnya'),
('A04.5', 'Campylobacter enteritis', 'Campylobacter enteritis'),
('A04.6', 'Enteritis due to Yersinia enterocolitica', 'Enteritis akibat Yersinia enterocolitica'),
('A04.7', 'Enterocolitis due to Clostridium difficile', 'Enterocolitis karena Clostridium difficile'),
('A04.8', 'Other specified bacterial intestinal infections', 'Infeksi usus lainnya akibat bakteri khusus'),
('A04.9', 'Bacterial intestinal infection, unspecified', 'Infeksi bakteri usus, tidak spesifik'),
('A05.0', 'Foodborne staphylococcal intoxication', 'Keracunan staphylococcal bawaan makanan'),
('A05.1', 'Botulism', 'Botulisme'),
('A05.2', 'Foodborne Clostridium perfringens [Clostridium welchii] intoxication', 'Keracunan Makanan akibat Perfringens Clostridium [ Clostridium welchii ]'),
('A05.3', 'Foodborne Vibrio parahaemolyticus intoxication', 'Keracunan Makanan akibat Vibrio parahaemolyticus'),
('A05.4', 'Foodborne Bacillus cereus intoxication', 'Keracunan makanan oleh Cereus Bacillus'),
('A05.8', 'Other specified bacterial foodborne intoxications', 'Keracunan makanan akibat bakteri lainnya'),
('A05.9', 'Bacterial foodborne intoxication, unspecified', 'Keracunan makanan akibat bakteri yang tidak spesifik'),
('A06.0', 'Acute amoebic dysentery', 'Disentri amuba akut'),
('A06.1', 'Chronic intestinal amoebiasis', 'Amoebiasis usus kronis'),
('A06.2', 'Amoebic nondysenteric colitis', 'Kolitis amuba nondysenteric'),
('A06.3', 'Amoeboma of intestine', 'Amoeboma usus'),
('A06.4', 'Amoebic liver abscess', 'Abses hati amuba'),
('A06.5', 'Amoebic lung abscess', 'Abses paru amuba'),
('A06.6', 'Amoebic brain abscess', 'Abses otak amuba'),
('A06.7', 'Cutaneous amoebiasis', 'Amoebiasis Cutaneous'),
('A06.8', 'Amoebic infection of other sites', 'Infeksi amuba lainnya'),
('A06.9', 'Amoebiasis, unspecified', 'Amoebiasis , tidak spesifik'),
('A07.0', 'Balantidiasis', 'Balantidiasis'),
('A07.1', 'Giardiasis [lambliasis]', 'Giardiasis [ lambliasis ]'),
('A07.2', 'Cryptosporidiosis', 'Cryptosporidiosis'),
('A07.3', 'Isosporiasis', 'Isosporiasis'),
('A07.8', 'Other specified protozoal intestinal diseases', 'Penyakit usus lainnya yang disebabkan protozoa lainnya'),
('A07.9', 'Protozoal intestinal disease, unspecified', 'Penyakit usus oleh protozoa , tidak spesifik'),
('A08.0', 'Rotaviral enteritis', 'Enteritis rotavirus'),
('A08.1', 'Acute gastroenteropathy due to Norwalk agent', 'Gastroenteropathy akut karena agen Norwalk'),
('A08.2', 'Adenoviral enteritis', 'enteritis adenoviral'),
('A08.3', 'Other viral enteritis', 'Enteritis virus lainnya'),
('A08.4', 'Viral intestinal infection, unspecified', 'Infeksi virus  usus, tidak spesifik'),
('A08.5', 'Other specified intestinal infections', 'Infeksi usus tertentu lainnya'),
('A09', 'Diarrhoea and gastroenteritis of presumed infectious origin', 'Diare dan gastroenteritis oleh penyebab penyakit menular'),
('A15.0', 'Tuberculosis of lung, confirmed by sputum microscopy with or without culture', 'TBC paru-paru , hasil konfirmasi mikroskop pada sputum dengan atau tanpa cultur'),
('A15.1', 'Tuberculosis of lung, confirmed by culture only', 'TBC paru-paru , yang hanya dikonfirmasi secara kultur'),
('A15.2', 'Tuberculosis of lung, confirmed histologically', 'TBC paru-paru , yang dikonfirmasi secara histologi'),
('A15.3', 'Tuberculosis of lung, confirmed by unspecified means', 'TBC paru-paru , yang dikonfirmasi dengan cara yang tidak spesifik'),
('A15.4', 'Tuberculosis of intrathoracic lymph nodes, confirmed bacteriologically and histologically', 'Tuberkulosis kelenjar getah bening intrathoracic , dikonfirmasi bakteriologis dan histologis'),
('A15.5', 'Tuberculosis of larynx, trachea and bronchus, confirmed bacteriologically and histologically', 'Tuberkulosis laring , trakea , dan bronkus , dikonfirmasi secara bakteriologis dan histologis'),
('A15.6', 'Tuberculous pleurisy, confirmed bacteriologically and histologically', 'Pleuritis tuberkulosa , dikonfirmasi secara bakteriologis dan histologis'),
('A15.7', 'Primary respiratory tuberculosis, confirmed bacteriologically and histologically', 'TBC pernafasan primer , dikonfirmasi secara bakteriologis dan histologis'),
('A15.8', 'Other respiratory tuberculosis, confirmed bacteriologically and histologically', 'TBC pernapasan lainnya , dikonfirmasi secara bakteriologis dan histologis'),
('A15.9', 'Respiratory tuberculosis unspecified, confirmed bacteriologically and histologically', 'TBC pernafasan tidak spesifik , dikonfirmasi secara bakteriologis dan histologis'),
('A16.0', 'Tuberculosis of lung, bacteriologically and histologically negative', 'TBC paru-paru , bakteriologis dan histologis negatif'),
('A16.1', 'Tuberculosis of lung, bacteriological and histological examination not done', 'TBC paru-paru , dengan pemeriksaan bakteriologis dan histologis yang tidak dilakukan'),
('A16.2', 'Tuberculosis of lung, without mention of bacteriological or histological confirmation', 'TBC paru-paru , tanpa adanya konfirmasi secara bakteriologis atau histologis'),
('A16.3', 'Tuberculosis of intrathoracic lymph nodes, without mention of bacteriological or histological confirmation', 'Tuberkulosis kelenjar getah bening intrathoracic , tanpa adanya konfirmasi bakteriologis atau histologis'),
('A16.4', 'Tuberculosis of larynx, trachea and bronchus, without mention of bacteriological or histological confirmation', 'Tuberkulosis laring , trakea , dan bronkus , tanpa adanya konfirmasi bakteriologis atau histologis'),
('A16.5', 'Tuberculous pleurisy, without mention of bacteriological or histological confirmation', 'Pleuritis tuberkulosa , tanpa adanya konfirmasi bakteriologis atau histologis'),
('A16.7', 'Primary respiratory tuberculosis without mention of bacteriological or histological confirmation', 'TBC pernafasan primer tanpa adanya konfirmasi bakteriologis atau histologis'),
('A16.8', 'Other respiratory tuberculosis, without mention of bacteriological or histological confirmation', 'TBC pernapasan lainnya , tanpa adanya konfirmasi bakteriologis atau histologis'),
('A16.9', 'Respiratory tuberculosis unspecified, without mention of bacteriological or histological confirmation', 'TBC pernafasan tidak spesifik , tanpa adanya konfirmasi bakteriologis atau histologis'),
('A17.0', 'Tuberculous meningitis', 'Meningitis TB'),
('A17.1', 'Meningeal tuberculoma', 'Tuberculoma meningeal'),
('A17.8', 'Other tuberculosis of nervous system', 'TB lain dari sistem saraf'),
('A17.9', 'Tuberculosis of nervous system, unspecified', 'Tuberkulosis sistem saraf , tidak spesifik'),
('A18.0', 'Tuberculosis of bones and joints', 'Tuberkulosis tulang dan sendi'),
('A18.1', 'Tuberculosis of genitourinary system', 'Tuberkulosis sistem genitourinari'),
('A18.2', 'Tuberculous peripheral lymphadenopathy', 'Limfadenopati perifer TB'),
('A18.3', 'Tuberculosis of intestines, peritoneum and mesenteric glands', 'TBC usus , peritoneum dan kelenjar mesenterika'),
('A18.4', 'Tuberculosis of skin and subcutaneous tissue', 'Tuberkulosis kulit dan jaringan subkutan'),
('A18.5', 'Tuberculosis of eye', 'Tuberkulosis mata'),
('A18.6', 'Tuberculosis of ear', 'Tuberkulosis telinga'),
('A18.7', 'Tuberculosis of adrenal glands', 'Tuberkulosis kelenjar adrenal'),
('A18.8', 'Tuberculosis of other specified organs', 'Tuberkulosis pada organ tertentu lainnya'),
('A19.0', 'Acute miliary tuberculosis of a single specified site', 'Tuberkulosis milier akut pada sebuah sistem tunggal tertentu'),
('A19.1', 'Acute miliary tuberculosis of multiple sites', 'Tuberkulosis milier akut pada beberapa sistem'),
('A19.2', 'Acute miliary tuberculosis, unspecified', 'Tuberkulosis milier akut , tidak spesifik'),
('A19.8', 'Other miliary tuberculosis', 'Tuberkulosis milier lainnya'),
('A19.9', 'Miliary tuberculosis, unspecified', 'Tuberkulosis milier , tidak spesifik'),
('A20.0', 'Bubonic plague', 'Penyakit pes'),
('A20.1', 'Cellulocutaneous plague', 'Wabah Cellulocutaneous'),
('A20.2', 'Pneumonic plague', 'Wabah pneumonia'),
('A20.3', 'Plague meningitis', 'Meningitis Plague'),
('A20.7', 'Septicaemic plague', 'Wabah septikemia'),
('A20.8', 'Other forms of plague', 'Bentuk lain dari wabah'),
('A20.9', 'Plague, unspecified', 'Wabah , tidak spesifik'),
('A21.0', 'Ulceroglandular tularaemia', 'Tularaemia Ulceroglandular'),
('A21.1', 'Oculoglandular tularaemia', 'Tularaemia Oculoglandular'),
('A21.2', 'Pulmonary tularaemia', 'Tularaemia paru'),
('A21.3', 'Gastrointestinal tularaemia', 'Tularaemia gastrointestinal'),
('A21.7', 'Generalized tularaemia', 'Tularaemia umum'),
('A21.8', 'Other forms of tularaemia', 'Bentuk lain dari tularaemia'),
('A21.9', 'Tularaemia, unspecified', 'Tularaemia , tidak spesifik'),
('A22.0', 'Cutaneous anthrax', 'Cutaneous anthrax'),
('A22.1', 'Pulmonary anthrax', 'Anthrax pada paru'),
('A22.2', 'Gastrointestinal anthrax', 'Anthrax pada gastrointestinal'),
('A22.7', 'Anthrax septicaemia', 'Anthrax pada septicemia'),
('A22.8', 'Other forms of anthrax', 'Bentuk lain dari anthrax'),
('A22.9', 'Anthrax, unspecified', 'Anthrax , tidak spesifik'),
('A23.0', 'Brucellosis due to Brucella melitensis', 'Brucellosis karena Brucella melitensis'),
('A23.1', 'Brucellosis due to Brucella abortus', 'Brucellosis karena Brucella abortus'),
('A23.2', 'Brucellosis due to Brucella suis', 'Brucellosis karena Brucella suis'),
('A23.3', 'Brucellosis due to Brucella canis', 'Brucellosis karena Brucella canis'),
('A23.8', 'Other brucellosis', 'Brucellosis lainnya'),
('A23.9', 'Brucellosis, unspecified', 'Brucellosis , tidak spesifik'),
('A24.0', 'Glanders', 'Sakit beringus'),
('A24.1', 'Acute and fulminating melioidosis', 'Melioidosis akut dan fulminan '),
('A24.2', 'Subacute and chronic melioidosis', 'Melioidosis subakut dan kronis '),
('A24.3', 'Other melioidosis', 'Melioidosis lainnya'),
('A24.4', 'Melioidosis, unspecified', 'Melioidosis , tidak spesifik'),
('A25.0', 'Spirillosis', 'Spirillosis'),
('A25.1', 'Streptobacillosis', 'Streptobacillosis'),
('A25.9', 'Rat-bite fever, unspecified', 'Demam gigitan tikus , tidak spesifik'),
('A26.0', 'Cutaneous erysipeloid', 'Erysipeloid Cutaneous'),
('A26.7', 'Erysipelothrix septicaemia', 'Erysipelothrix septicemia'),
('A26.8', 'Other forms of erysipeloid', 'Bentuk lain dari erysipeloid'),
('A26.9', 'Erysipeloid, unspecified', 'Erysipeloid , tidak spesifik'),
('A27.0', 'Leptospirosis icterohaemorrhagica', 'Leptospirosis icterohaemorrhagica'),
('A27.8', 'Other forms of leptospirosis', 'Bentuk lain dari leptospirosis'),
('A27.9', 'Leptospirosis, unspecified', 'Leptospirosis , tidak spesifik'),
('A28.0', 'Pasteurellosis', 'Pasteurellosis'),
('A28.1', 'Cat-scratch disease', 'Penyakit Cat- scratch'),
('A28.2', 'Extraintestinal yersiniosis', 'mikroorganisme ini adalah Yersiniosis ekstraintestinal'),
('A28.8', 'Other specified zoonotic bacterial diseases, not elsewhere classified', 'Penyakit bakteri lainnya yang spesifik secara zoonosis , tidak diklasifikasikan pada tempat lain'),
('A28.9', 'Zoonotic bacterial disease, unspecified', 'Penyakit bakteri zoonosis , tidak spesifik'),
('A30.0', 'Indeterminate leprosy', 'Kusta Indeterminasi'),
('A30.1', 'Tuberculoid leprosy', 'Kusta tuberkuloid'),
('A30.2', 'Borderline tuberculoid leprosy', 'Borderline tuberkuloid kusta'),
('A30.3', 'Borderline leprosy', 'Kusta borderline'),
('A30.4', 'Borderline lepromatous leprosy', 'Borderline kusta lepromatous'),
('A30.5', 'Lepromatous leprosy', 'Kusta lepromatous'),
('A30.8', 'Other forms of leprosy', 'Bentuk lain dari kusta'),
('A30.9', 'Leprosy, unspecified', 'Kusta , tidak spesifik'),
('A31.0', 'Pulmonary mycobacterial infection', 'Infeksi mikobakteri paru'),
('A31.1', 'Cutaneous mycobacterial infection', 'Infeksi mikobakteri Cutaneous'),
('A31.8', 'Other mycobacterial infections', 'Infeksi mikobakteri lainnya'),
('A31.9', 'Mycobacterial infection, unspecified', 'Infeksi mikobakterium , tidak spesifik'),
('A32.0', 'Cutaneous listeriosis', 'listeriosis Cutaneous'),
('A32.1', 'Listerial meningitis and meningoencephalitis', 'Meningitis listeria dan meningoencephalitis'),
('A32.7', 'Listerial septicaemia', 'Septikemia listeria'),
('A32.8', 'Other forms of listeriosis', 'Bentuk lain dari listeriosis'),
('A32.9', 'Listeriosis, unspecified', 'Listeriosis , tidak spesifik'),
('A33', 'Tetanus neonatorum', 'Tetanus neonatorum'),
('A34', 'Obstetrical tetanus', 'Tetanus kandungan'),
('A35', 'Other tetanus', 'Tetanus lainnya'),
('A36.0', 'Pharyngeal diphtheria', 'Difteri pada faring'),
('A36.1', 'Nasopharyngeal diphtheria', 'Difteri pada nasofaring'),
('A36.2', 'Laryngeal diphtheria', 'Difteri pada laring'),
('A36.3', 'Cutaneous diphtheria', 'Difteri Cutaneous'),
('A36.8', 'Other diphtheria', 'Difteri lainnya'),
('A36.9', 'Diphtheria, unspecified', 'Difteri , tidak spesifik'),
('A37.0', 'Whooping cough due to Bordetella pertussis', 'Rejan batuk karena Bordetella pertussis'),
('A37.1', 'Whooping cough due to Bordetella parapertussis', 'Rejan batuk karena Bordetella parapertussis'),
('A37.8', 'Whooping cough due to other Bordetella species', 'Batuk rejan karena spesies Bordetella lainnya'),
('A37.9', 'Whooping cough, unspecified', 'Batuk rejan , tidak spesifik'),
('A38', 'Scarlet fever', 'Demam berdarah'),
('A39.0', 'Meningococcal meningitis', 'Meningitis meningokokus'),
('A39.1', 'Waterhouse-Friderichsen syndrome', 'Sindrom Waterhouse - Friderichsen'),
('A39.2', 'Acute meningococcaemia', 'Meningokoksemia akut'),
('A39.3', 'Chronic meningococcaemia', 'Meningokoksemia kronis'),
('A39.4', 'Meningococcaemia, unspecified', 'Meningokoksemia , tidak spesifik'),
('A39.5', 'Meningococcal heart disease', 'Penyakit jantung Meningokokus'),
('A39.8', 'Other meningococcal infections', 'Infeksi meningokokus lainnya'),
('A39.9', 'Meningococcal infection, unspecified', 'Infeksi meningokokus , tidak spesifik'),
('A40.0', 'Septicaemia due to streptococcus, group A', 'Septicaemia karena streptokokus grup A'),
('A40.1', 'Septicaemia due to streptococcus, group B', 'Septicaemia karena streptococcus , kelompok B'),
('A40.2', 'Septicaemia due to streptococcus, group D', 'Septicaemia karena streptococcus , kelompok D'),
('A40.3', 'Septicaemia due to Streptococcus pneumoniae', 'Septicaemia karena Streptococcus pneumoniae'),
('A40.8', 'Other streptococcal septicaemia', 'Septikemia streptokokus lainnya'),
('A40.9', 'Streptococcal septicaemia, unspecified', 'Septikemia streptokokus , tidak spesifik'),
('A41.0', 'Septicaemia due to Staphylococcus aureus', 'Septicaemia karena Staphylococcus aureus'),
('A41.1', 'Septicaemia due to other specified staphylococcus', 'Septicaemia karena staphylococcus tertentu lainnya'),
('A41.2', 'Septicaemia due to unspecified staphylococcus', 'Septicaemia karena staphylococcus yang tidak spesifik'),
('A41.3', 'Septicaemia due to Haemophilus influenzae', 'Septicaemia karena Haemophilus influenzae'),
('A41.4', 'Septicaemia due to anaerobes', 'Septicaemia karena anaerob'),
('A41.5', 'Septicaemia due to other Gram-negative organisms', 'Septicaemia karena organisme Gram - negatif lainnya'),
('A41.8', 'Other specified septicaemia', 'Septikemia tertentu lainnya'),
('A41.9', 'Septicaemia, unspecified', 'Septicaemia , tidak spesifik'),
('A42.0', 'Pulmonary actinomycosis', 'Actinomycosis paru'),
('A42.1', 'Abdominal actinomycosis', 'Actinomycosis perut'),
('A42.2', 'Cervicofacial actinomycosis', 'Actinomycosis cervicofacial'),
('A42.7', 'Actinomycotic septicaemia', 'Septikemia Actinomycotic'),
('A42.8', 'Other forms of actinomycosis', 'Bentuk lain dari actinomycosis'),
('A42.9', 'Actinomycosis, unspecified', 'Actinomycosis , tidak spesifik'),
('A43.0', 'Pulmonary nocardiosis', 'Nocardiosis paru'),
('A43.1', 'Cutaneous nocardiosis', 'Nocardiosis Cutaneous'),
('A43.8', 'Other forms of nocardiosis', 'Bentuk lain dari nocardiosis'),
('A43.9', 'Nocardiosis, unspecified', 'Nocardiosis , tidak spesifik'),
('A44.0', 'Systemic bartonellosis', 'Bartonellosis sistemik'),
('A44.1', 'Cutaneous and mucocutaneous bartonellosis', 'Cutaneous dan mukokutan bartonellosis'),
('A44.8', 'Other forms of bartonellosis', 'Bentuk lain dari bartonellosis'),
('A44.9', 'Bartonellosis, unspecified', 'Bartonellosis , tidak spesifik'),
('A46', 'Erysipelas', 'Luka Api'),
('A48.0', 'Gas gangrene', 'Gangren gas'),
('A48.1', 'Legionnaires disease', 'Penyakit Legionnaires'),
('A48.2', 'Nonpneumonic Legionnaires disease [Pontiac fever]', 'Penyakit Legionnaires Nonpneumonic [ Pontiac demam ]'),
('A48.3', 'Toxic shock syndrome', 'Toxic shock syndrome'),
('A48.4', 'Brazilian purpuric fever', 'Demam purpura Brasil'),
('A48.8', 'Other specified bacterial diseases', 'Penyakit bakteri lainnya yang spesifik'),
('A49.0', 'Staphylococcal infection, unspecified', 'Infeksi stafilokokus , tidak spesifik'),
('A49.1', 'Streptococcal infection, unspecified', 'Infeksi streptokokus , tidak spesifik'),
('A49.2', 'Haemophilus influenzae infection, unspecified', 'Infeksi influenzae Haemophilus , tidak spesifik'),
('A49.3', 'Mycoplasma infection, unspecified', 'Infeksi Mycoplasma , tidak spesifik'),
('A49.8', 'Other bacterial infections of unspecified site', 'Infeksi bakteri lain dari situs yang tidak spesifik'),
('A49.9', 'Bacterial infection, unspecified', 'Infeksi bakteri , tidak spesifik'),
('A50.0', 'Early congenital syphilis, symptomatic', 'Sifilis kongenital dini, gejala'),
('A50.1', 'Early congenital syphilis, latent', 'Sifilis kongenital dini, laten'),
('A50.2', 'Early congenital syphilis, unspecified', 'Sifilis kongenital dini, tidak spesifik'),
('A50.3', 'Late congenital syphilitic oculopathy', 'Akhir oculopathy sifilis kongenital'),
('A50.4', 'Late congenital neurosyphilis [juvenile neurosyphilis]', 'Neurosifilis kongenital Akhir [ remaja neurosifilis ]'),
('A50.5', 'Other late congenital syphilis, symptomatic', 'Sifilis kongenital lainnya , gejala'),
('A50.6', 'Late congenital syphilis, latent', 'Sifilis kongenital terlambat , laten'),
('A50.7', 'Late congenital syphilis, unspecified', 'Sifilis kongenital terlambat , tidak spesifik'),
('A50.9', 'Congenital syphilis, unspecified', 'Sifilis kongenital , tidak spesifik'),
('A51.0', 'Primary genital syphilis', 'Sifilis genital primer'),
('A51.1', 'Primary anal syphilis', 'Sifilis anal Primer'),
('A51.2', 'Primary syphilis of other sites', 'Sifilis primer dari situs lain'),
('A51.3', 'Secondary syphilis of skin and mucous membranes', 'Sifilis sekunder dari kulit dan membran mukosa'),
('A51.4', 'Other secondary syphilis', 'Sifilis sekunder lainnya'),
('A51.5', 'Early syphilis, latent', 'Sifilis awal , laten'),
('A51.9', 'Early syphilis, unspecified', 'Sifilis awal , tidak spesifik'),
('A52.0', 'Cardiovascular syphilis', 'Sifilis kardiovaskular'),
('A52.1', 'Symptomatic neurosyphilis', 'Neurosifilis simtomatik'),
('A52.2', 'Asymptomatic neurosyphilis', 'Neurosifilis asimtomatik'),
('A52.3', 'Neurosyphilis, unspecified', 'Neurosifilis , tidak spesifik'),
('A52.7', 'Other symptomatic late syphilis', 'Beberapa gejala lain dari sifilis'),
('A52.8', 'Late syphilis, latent', 'Sifilis , laten'),
('A52.9', 'Late syphilis, unspecified', 'Sifilis , tidak spesifik'),
('A53.0', 'Latent syphilis, unspecified as early or late', 'Sifilis laten , tidak spesifik pada awal atau akhir'),
('A53.9', 'Syphilis, unspecified', 'Sifilis , tidak spesifik'),
('A54.0', 'Gonococcal infection of lower genitourinary tract without periurethral or accessory gland abscess', 'Infeksi gonokokal saluran genitourinari rendah tanpa periurethral atau aksesori kelenjar abses'),
('A54.1', 'Gonococcal infection of lower genitourinary tract with periurethral and accessory gland abscess', 'Infeksi gonokokal saluran genitourinari rendah dengan periurethral dan aksesori kelenjar abses'),
('A54.2', 'Gonococcal pelviperitonitis and other gonococcal genitourinary infections', 'Pelviperitonitis gonokokal dan infeksi genitourinari gonokokal lainnya'),
('A54.3', 'Gonococcal infection of eye', 'Infeksi gonokokal mata'),
('A54.4', 'Gonococcal infection of musculoskeletal system', 'Infeksi gonokokal sistem muskuloskeletal'),
('A54.5', 'Gonococcal pharyngitis', 'faringitis gonokokal'),
('A54.6', 'Gonococcal infection of anus and rectum', 'Infeksi gonokokal dari anus dan rektum'),
('A54.8', 'Other gonococcal infections', 'Infeksi gonokokal lainnya'),
('A54.9', 'Gonococcal infection, unspecified', 'Infeksi gonokokal , tidak spesifik'),
('A55', 'Chlamydial lymphogranuloma (venereum)', 'Klamidia limfogranuloma ( venereum )'),
('A56.0', 'Chlamydial infection of lower genitourinary tract', 'Infeksi klamidia saluran genitourinari rendah'),
('A56.1', 'Chlamydial infection of pelviperitoneum and other genitourinary organs', 'Infeksi klamidia dari pelviperitoneum dan organ genitourinari lainnya'),
('A56.2', 'Chlamydial infection of genitourinary tract, unspecified', 'Infeksi klamidia saluran genitourinaria , tidak spesifik'),
('A56.3', 'Chlamydial infection of anus and rectum', 'Infeksi klamidia dari anus dan rektum'),
('A56.4', 'Chlamydial infection of pharynx', 'Infeksi klamidia faring'),
('A56.8', 'Sexually transmitted chlamydial infection of other sites', 'Infeksi menular klamidia secara seksual pada situs lain'),
('A57', 'Chancroid', 'Chancroid'),
('A58', 'Granuloma inguinale', 'Granuloma inguinale'),
('A59.0', 'Urogenital trichomoniasis', 'Trikomoniasis urogenital'),
('A59.8', 'Trichomoniasis of other sites', 'Trikomoniasis situs lain'),
('A59.9', 'Trichomoniasis, unspecified', 'Trikomoniasis , tidak spesifik'),
('A60.0', 'Herpesviral infection of genitalia and urogenital tract', 'Infeksi Herpesviral alat kelamin dan saluran urogenital'),
('A60.1', 'Herpesviral infection of perianal skin and rectum', 'Infeksi Herpesviral kulit perianal dan rektum'),
('A60.9', 'Anogenital herpesviral infection, unspecified', 'Infeksi herpesviral anogenital , tidak spesifik'),
('A63.0', 'Anogenital (venereal) warts', 'Anogenital ( kelamin ) kutil'),
('A63.8', 'Other specified predominantly sexually transmitted diseases', 'Penyakit tertentu lainnya terutama menular seksual'),
('A64', 'Unspecified sexually transmitted disease', 'Penyakit menular seksual yang tidak spesifik'),
('A65', 'Nonvenereal syphilis', 'Sifilis nonvenereal'),
('A66.0', 'Initial lesions of yaws', 'Lesi awal patek'),
('A66.1', 'Multiple papillomata and wet crab yaws', 'Beberapa papillomata dan kepiting patek basah'),
('A66.2', 'Other early skin lesions of yaws', 'Lesi kulit awal lain dari patek'),
('A66.3', 'Hyperkeratosis of yaws', 'Hiperkeratosis dari patek'),
('A66.4', 'Gummata and ulcers of yaws', 'Gummata dan borok dari patek'),
('A66.5', 'Gangosa', 'Gangosa'),
('A66.6', 'Bone and joint lesions of yaws', 'Tulang dan lesi bersama patek'),
('A66.7', 'Other manifestations of yaws', 'Manifestasi lain dari patek'),
('A66.8', 'Latent yaws', 'Patek laten'),
('A66.9', 'Yaws, unspecified', 'Patek , tidak spesifik'),
('A67.0', 'Primary lesions of pinta', 'Lesi primer pinta'),
('A67.1', 'Intermediate lesions of pinta', 'Lesi menengah pinta'),
('A67.2', 'Late lesions of pinta', 'Lesi akhir pinta'),
('A67.3', 'Mixed lesions of pinta', 'Lesi campuran dari pinta'),
('A67.9', 'Pinta, unspecified', 'Pinta , tidak spesifik'),
('A68.0', 'Louse-borne relapsing fever', 'Demam kambuh kutu - ditanggung'),
('A68.1', 'Tick-borne relapsing fever', 'Demam kambuh tick-borne'),
('A68.9', 'Relapsing fever, unspecified', 'Demam kambuh , tidak spesifik'),
('A69.0', 'Necrotizing ulcerative stomatitis', 'Necrotizing stomatitis ulseratif'),
('A69.1', 'Other Vincents infections', 'Infeksi Vincents lainnya'),
('A69.2', 'Lyme disease', 'Penyakit Lyme'),
('A69.8', 'Other specified spirochaetal infections', 'Infeksi spirochaetal tertentu lainnya'),
('A69.9', 'Spirochaetal infection, unspecified', 'Infeksi Spirochaetal , tidak spesifik'),
('A70', 'Chlamydia psittaci infection', 'Infeksi Chlamydia psittaci'),
('A71.0', 'Initial stage of trachoma', 'Tahap awal trachoma'),
('A71.1', 'Active stage of trachoma', 'Tahap aktif trachoma'),
('A71.9', 'Trachoma, unspecified', 'Trachoma , tidak spesifik'),
('A74.0', 'Chlamydial conjunctivitis', 'Konjungtivitis klamidia'),
('A74.8', 'Other chlamydial diseases', 'Penyakit klamidia lainnya'),
('A74.9', 'Chlamydial infection, unspecified', 'Infeksi klamidia , tidak spesifik'),
('A75.0', 'Epidemic louse-borne typhus fever due to Rickettsia prowazekii', 'Epidemi kutu - ditanggung tifus demam akibat prowazekii Rickettsia'),
('A75.1', 'Recrudescent typhus [Brills disease]', 'Tifus yg timbul [ penyakit Brills ]'),
('A75.2', 'Typhus fever due to Rickettsia typhi', 'Demam tipus karena typhi Rickettsia'),
('A75.3', 'Typhus fever due to Rickettsia tsutsugamushi', 'Demam tipus karena tsutsugamushi Rickettsia'),
('A75.9', 'Typhus fever, unspecified', 'Demam Tifus , tidak spesifik'),
('A77.0', 'Spotted fever due to Rickettsia rickettsii', 'Spotted demam akibat rickettsii Rickettsia'),
('A77.1', 'Spotted fever due to Rickettsia conorii', 'Spotted demam akibat conorii Rickettsia'),
('A77.2', 'Spotted fever due to Rickettsia sibirica', 'Spotted demam karena Rickettsia sibirica'),
('A77.3', 'Spotted fever due to Rickettsia australis', 'Spotted demam akibat australis Rickettsia'),
('A77.8', 'Other spotted fevers', 'Demam berbintik lainnya'),
('A77.9', 'Spotted fever, unspecified', 'Demam Spotted , tidak spesifik'),
('A78', 'Q fever', 'Demam Q '),
('A79.0', 'Trench fever', 'Demam parit'),
('A79.1', 'Rickettsialpox due to Rickettsia akari', 'Rickettsialpox karena Rickettsia akari'),
('A79.8', 'Other specified rickettsioses', 'Rickettsioses tertentu lainnya'),
('A79.9', 'Rickettsiosis, unspecified', 'Rickettsiosis , tidak spesifik'),
('A80.0', 'Acute paralytic poliomyelitis, vaccine-associated', 'Poliomyelitis paralitik akut , vaksin terkait'),
('A80.1', 'Acute paralytic poliomyelitis, wild virus, imported', 'Poliomyelitis paralitik akut , virus liar , diimpor'),
('A80.2', 'Acute paralytic poliomyelitis, wild virus, indigenous', 'Poliomyelitis paralitik akut , virus liar , adat'),
('A80.3', 'Acute paralytic poliomyelitis, other and unspecified', 'Akut poliomyelitis paralitik , lain dan tidak spesifik'),
('A80.4', 'Acute nonparalytic poliomyelitis', 'Poliomyelitis nonparalytic akut'),
('A80.9', 'Acute poliomyelitis, unspecified', 'Poliomyelitis akut , tidak spesifik'),
('A81.0', 'Creutzfeldt-Jakob disease', 'Penyakit Creutzfeldt - Jakob'),
('A81.1', 'Subacute sclerosing panencephalitis', 'Subakut sclerosing panencephalitis'),
('A81.2', 'Progressive multifocal leukoencephalopathy', 'Progressive multifocal leukoencephalopathy'),
('A81.8', 'Other atypical virus infections of central nervous system', 'Infeksi virus atipikal lain dari sistem saraf pusat'),
('A81.9', 'Atypical virus infection of central nervous system, unspecified', 'Infeksi virus atipikal sistem saraf pusat , tidak spesifik'),
('A82.0', 'Sylvatic rabies', 'Rabies sylvatic'),
('A82.1', 'Urban rabies', 'Rabies perkotaan'),
('A82.9', 'Rabies, unspecified', 'Rabies , tidak spesifik'),
('A83.0', 'Japanese encephalitis', 'Japanese ensefalitis'),
('A83.1', 'Western equine encephalitis', 'Ensefalitis kuda Barat'),
('A83.2', 'Eastern equine encephalitis', 'Ensefalitis kuda Timur'),
('A83.3', 'St Louis encephalitis', 'Ensefalitis St Louis '),
('A83.4', 'Australian encephalitis', 'Ensefalitis Australia'),
('A83.5', 'California encephalitis', 'Ensefalitis California '),
('A83.6', 'Rocio virus disease', 'Penyakit virus Rocio'),
('A83.8', 'Other mosquito-borne viral encephalitis', 'Ensefalitis viral yang ditularkan dari virus nyamuk lainnya'),
('A83.9', 'Mosquito-borne viral encephalitis, unspecified', 'Ensefalitis virus oleh nyamuk, tidak spesifik'),
('A84.0', 'Far Eastern tick-borne encephalitis [Russian spring-summer encephalitis]', 'Tick-borne Far Eastern ensefalitis [ Rusia ensefalitis semi-musim panas ]'),
('A84.1', 'Central European tick-borne encephalitis', 'Tick-borne Eropa Tengah ensefalitis'),
('A84.8', 'Other tick-borne viral encephalitis', 'Lain tick-borne ensefalitis viral'),
('A84.9', 'Tick-borne viral encephalitis, unspecified', 'Tick ??-borne ensefalitis virus , tidak spesifik'),
('A85.0', 'Enteroviral encephalitis', 'Ensefalitis enterovirus'),
('A85.1', 'Adenoviral encephalitis', 'Ensefalitis adenoviral'),
('A85.2', 'Arthropod-borne viral encephalitis, unspecified', 'Arthropod -borne ensefalitis virus , tidak spesifik'),
('A85.8', 'Other specified viral encephalitis', 'Lain ensefalitis virus tertentu'),
('A86', 'Unspecified viral encephalitis', 'Ensefalitis virus yang tidak spesifik'),
('A87.0', 'Enteroviral meningitis', 'Meningitis enterovirus'),
('A87.1', 'Adenoviral meningitis', 'Meningitis adenoviral'),
('A87.2', 'Lymphocytic choriomeningitis', 'Choriomeningitis limfositik'),
('A87.8', 'Other viral meningitis', 'Meningitis viral lainnya'),
('A87.9', 'Viral meningitis, unspecified', 'Viral meningitis , tidak spesifik'),
('A88.0', 'Enteroviral exanthematous fever [Boston exanthem]', 'Demam exanthematous enterovirus [ Boston exanthem ]'),
('A88.1', 'Epidemic vertigo', 'Epidemi vertigo'),
('A88.8', 'Other specified viral infections of central nervous system', 'Infeksi virus tertentu lainnya dari sistem saraf pusat'),
('A89', 'Unspecified viral infection of central nervous system', 'Infeksi virus yang tidak spesifik sistem saraf pusat'),
('A90', 'Dengue fever [classical dengue]', 'Demam berdarah [ dengue klasik ]'),
('A91', 'Dengue haemorrhagic fever', 'Demam berdarah dengue'),
('A92.0', 'Chikungunya virus disease', 'Penyakit virus Chikungunya'),
('A92.1', 'Onyong-nyong fever', 'Demam Onyong - nyong'),
('A92.2', 'Venezuelan equine fever', 'Demam kuda Venezuela'),
('A92.3', 'West Nile fever', 'Demam West Nile'),
('A92.4', 'Rift Valley fever', 'Demam Rift Valley'),
('A92.8', 'Other specified mosquito-borne viral fevers', 'Demam nyamuk tertentu lainnya viral'),
('A92.9', 'Mosquito-borne viral fever, unspecified', 'Demam virus nyamuk , tidak spesifik'),
('A93.0', 'Oropouche virus disease', 'Penyakit virus Oropouche'),
('A93.1', 'Sandfly fever', 'Demam Sandfly'),
('A93.2', 'Colorado tick fever', 'Demam kutu Colorado'),
('A93.8', 'Other specified arthropod-borne viral fevers', 'Demam arthropoda -borne virus tertentu lainnya'),
('A94', 'Unspecified arthropod-borne viral fever', 'Demam virus arthropoda -borne Unspecified'),
('A95.0', 'Sylvatic yellow fever', 'Demam kuning sylvatic'),
('A95.1', 'Urban yellow fever', 'Demam kuning perkotaan'),
('A95.9', 'Yellow fever, unspecified', 'Demam kuning , tidak spesifik'),
('A96.0', 'Junin haemorrhagic fever', 'Demam berdarah Junin'),
('A96.1', 'Machupo haemorrhagic fever', 'Demam berdarah Machupo'),
('A96.2', 'Lassa fever', 'Demam Lassa'),
('A96.8', 'Other arenaviral haemorrhagic fevers', 'Demam berdarah arenaviral lainnya'),
('A96.9', 'Arenaviral haemorrhagic fever, unspecified', 'Demam berdarah Arenaviral , tidak spesifik'),
('A98.0', 'Crimean-Congo haemorrhagic fever', 'Demam berdarah Krimea - Kongo'),
('A98.1', 'Omsk haemorrhagic fever', 'Demam berdarah Omsk'),
('A98.2', 'Kyasanur Forest disease', 'Penyakit Kyasanur Forest'),
('A98.3', 'Marburg virus disease', 'Penyakit virus Marburg'),
('A98.4', 'Ebola virus disease', 'Penyakit virus Ebola'),
('A98.5', 'Haemorrhagic fever with renal syndrome', 'Demam berdarah dengan sindrom renal'),
('A98.8', 'Other specified viral haemorrhagic fevers', 'Demam berdarah lainnya yang spesifik virus'),
('A99', 'Unspecified viral haemorrhagic fever', 'Demam berdarah virus yang tidak spesifik'),
('B00.0', 'Eczema herpeticum', 'Eksim herpeticum'),
('B00.1', 'Herpesviral vesicular dermatitis', 'Dermatitis vesikuler Herpesviral'),
('B00.2', 'Herpesviral gingivostomatitis and pharyngotonsillitis', 'Gingivostomatitis Herpesviral dan faringotonsilitis'),
('B00.3', 'Herpesviral meningitis', 'Meningitis Herpesviral'),
('B00.4', 'Herpesviral encephalitis', 'Ensefalitis Herpesviral'),
('B00.5', 'Herpesviral ocular disease', 'Penyakit mata Herpesviral'),
('B00.7', 'Disseminated herpesviral disease', 'Penyakit herpesviral disebarluaskan'),
('B00.8', 'Other forms of herpesviral infection', 'Bentuk lain dari infeksi herpesviral'),
('B00.9', 'Herpesviral infection, unspecified', 'Infeksi Herpesviral , tidak spesifik'),
('B01.0', 'Varicella meningitis', 'Varicella meningitis'),
('B01.1', 'Varicella encephalitis', 'Varicella ensefalitis'),
('B01.2', 'Varicella pneumonia', 'Varicella pneumonia'),
('B01.8', 'Varicella with other complications', 'Varicella dengan komplikasi lain'),
('B01.9', 'Varicella without complication', 'Varicella tanpa komplikasi'),
('B02.0', 'Zoster encephalitis', 'Zoster ensefalitis'),
('B02.1', 'Zoster meningitis', 'Zoster meningitis'),
('B02.2', 'Zoster with other nervous system involvement', 'Zoster dengan keterlibatan sistem saraf lainnya'),
('B02.3', 'Zoster ocular disease', 'Zoster penyakit mata'),
('B02.7', 'Disseminated zoster', 'Diseminata zoster'),
('B02.8', 'Zoster with other complications', 'Zoster dengan komplikasi lain'),
('B02.9', 'Zoster without complication', 'Zoster tanpa komplikasi'),
('B03', 'Smallpox', 'Cacar'),
('B04', 'Monkeypox', 'Monkeypox'),
('B05.0', 'Measles complicated by encephalitis', 'Campak rumit oleh ensefalitis'),
('B05.1', 'Measles complicated by meningitis', 'Campak rumit oleh meningitis'),
('B05.2', 'Measles complicated by pneumonia', 'Campak rumit oleh pneumonia'),
('B05.3', 'Measles complicated by otitis media', 'Campak rumit oleh otitis media'),
('B05.4', 'Measles with intestinal complications', 'Campak dengan komplikasi usus'),
('B05.8', 'Measles with other complications', 'Campak dengan komplikasi lain'),
('B05.9', 'Measles without complication', 'Campak tanpa komplikasi'),
('B06.0', 'Rubella with neurological complications', 'Rubella dengan komplikasi neurologis'),
('B06.8', 'Rubella with other complications', 'Rubella dengan komplikasi lain'),
('B06.9', 'Rubella without complication', 'Rubella tanpa komplikasi'),
('B07', 'Viral warts', 'Kutil viral'),
('B08.0', 'Other orthopoxvirus infections', 'Infeksi orthopoxvirus lainnya'),
('B08.1', 'Molluscum contagiosum', 'Moluskum kontagiosum'),
('B08.2', 'Exanthema subitum [sixth disease]', 'Eksantema subitum [ penyakit keenam ]'),
('B08.3', 'Erythema infectiosum [fifth disease]', 'Eritema infectiosum [ penyakit kelima ]'),
('B08.4', 'Enteroviral vesicular stomatitis with exanthem', 'Enterovirus stomatitis vesikuler dengan exanthem'),
('B08.5', 'Enteroviral vesicular pharyngitis', 'Enterovirus faringitis vesikuler'),
('B08.8', 'Other specified viral infections characterized by skin and mucous membrane lesions', 'Infeksi virus tertentu lainnya ditandai oleh kulit dan lesi selaput lendir'),
('B09', 'Unspecified viral infection characterized by skin and mucous membrane lesions', 'Infeksi virus yang tidak spesifik ditandai dengan kulit dan lesi selaput lendir'),
('B15.0', 'Hepatitis A with hepatic coma', 'Hepatitis A dengan koma hepatik'),
('B15.9', 'Hepatitis A without hepatic coma', 'Hepatitis A tanpa koma hepatik'),
('B16.0', 'Acute hepatitis B with delta-agent (coinfection) with hepatic coma', 'Hepatitis B akut dengan delta -agent ( koinfeksi ) dengan koma hepatik'),
('B16.1', 'Acute hepatitis B with delta-agent (coinfection) without hepatic coma', 'Hepatitis B akut dengan delta -agent ( koinfeksi ) tanpa koma hepatik'),
('B16.2', 'Acute hepatitis B without delta-agent with hepatic coma', 'Hepatitis B akut tanpa delta - agen dengan koma hepatik'),
('B16.9', 'Acute hepatitis B without delta-agent and without hepatic coma', 'Hepatitis B akut tanpa delta -agent dan tanpa koma hepatik'),
('B17.0', 'Acute delta-(super)infection of hepatitis B carrier', 'Akut delta - (super ) infeksi hepatitis B pembawa'),
('B17.1', 'Acute hepatitis C', 'Akut hepatitis C'),
('B17.2', 'Acute hepatitis E', 'Akut hepatitis E'),
('B17.8', 'Other specified acute viral hepatitis', 'Lainnya yang spesifik hepatitis virus akut'),
('B18.0', 'Chronic viral hepatitis B with delta-agent', 'Kronis virus hepatitis B dengan delta - agen'),
('B18.1', 'Chronic viral hepatitis B without delta-agent', 'Kronis virus hepatitis B tanpa delta - agen'),
('B18.2', 'Chronic viral hepatitis C', 'Hepatitis C virus kronis'),
('B18.8', 'Other chronic viral hepatitis', 'Lain hepatitis virus kronis'),
('B18.9', 'Chronic viral hepatitis, unspecified', 'Hepatitis virus kronis , tidak spesifik'),
('B19.0', 'Unspecified viral hepatitis hepatic with coma', 'Tidak disebutkan hepatitis virus hati dengan koma'),
('B19.9', 'Unspecified viral hepatitis without hepatic coma', 'Hepatitis virus yang tidak spesifik tanpa koma hepatik'),
('B20.0', 'HIV disease resulting in mycobacterial infection', 'Penyakit HIV mengakibatkan infeksi mikobakteri'),
('B20.1', 'HIV disease resulting in other bacterial infections', 'Penyakit HIV mengakibatkan infeksi bakteri lainnya'),
('B20.2', 'HIV disease resulting in cytomegaloviral disease', 'Penyakit HIV mengakibatkan penyakit cytomegaloviral'),
('B20.3', 'HIV disease resulting in other viral infections', 'Penyakit HIV mengakibatkan infeksi virus lainnya'),
('B20.4', 'HIV disease resulting in candidiasis', 'Penyakit HIV mengakibatkan candidiasis'),
('B20.5', 'HIV disease resulting in other mycoses', 'Penyakit HIV mengakibatkan mikosis lain'),
('B20.6', 'HIV disease resulting in Pneumocystis carinii pneumonia', 'Penyakit HIV mengakibatkan pneumonia Pneumocystis carinii'),
('B20.7', 'HIV disease resulting in multiple infections', 'Penyakit HIV mengakibatkan beberapa infeksi'),
('B20.8', 'HIV disease resulting in other infectious and parasitic diseases', 'Penyakit HIV mengakibatkan penyakit infeksi dan parasit lainnya'),
('B20.9', 'HIV disease resulting in unspecified infectious or parasitic disease', 'Penyakit HIV mengakibatkan penyakit infeksi atau parasit yang tidak spesifik'),
('B21.0', 'HIV disease resulting in Kaposis sarcoma', 'Penyakit HIV mengakibatkan Kaposis sarkoma'),
('B21.1', 'HIV disease resulting in Burkitts lymphoma', 'Penyakit HIV mengakibatkan limfoma Burkitts'),
('B21.2', 'HIV disease resulting in other types of non-Hodgkins lymphoma', 'Penyakit HIV mengakibatkan jenis limfoma non - Hodgkins'),
('B21.3', 'HIV disease resulting in other malignant neoplasms of lymphoid, haematopoietic and related tissue', 'Penyakit HIV mengakibatkan neoplasma ganas lainnya limfoid , haematopoietic dan jaringan terkait'),
('B21.7', 'HIV disease resulting in multiple malignant neoplasms', 'Penyakit HIV mengakibatkan beberapa neoplasma ganas'),
('B21.8', 'HIV disease resulting in other malignant neoplasms', 'Penyakit HIV mengakibatkan neoplasma ganas lainnya'),
('B21.9', 'HIV disease resulting in unspecified malignant neoplasm', 'Penyakit HIV sehingga tidak spesifik neoplasma ganas'),
('B22.0', 'HIV disease resulting in encephalopathy', 'Penyakit HIV mengakibatkan ensefalopati'),
('B22.1', 'HIV disease resulting in lymphoid interstitial pneumonitis', 'Penyakit HIV mengakibatkan limfoid interstitial pneumonitis'),
('B22.2', 'HIV disease resulting in wasting syndrome', 'Penyakit HIV mengakibatkan wasting syndrome'),
('B22.7', 'HIV disease resulting in multiple diseases classified elsewhere', 'Penyakit HIV mengakibatkan beberapa penyakit diklasifikasikan di tempat lain'),
('B23.0', 'Acute HIV infection syndrome', 'Sindrom Infeksi akut HIV'),
('B23.1', 'HIV disease resulting in (persistent) generalized lymphadenopathy', 'Penyakit HIV mengakibatkan ( persisten ) limfadenopati generalisata'),
('B23.2', 'HIV disease resulting in haematological and immunological abnormalities, not elsewhere classified', 'Penyakit HIV mengakibatkan kelainan hematologis dan imunologi , tidak diklasifikasikan di tempat lain'),
('B23.8', 'HIV disease resulting in other specified conditions', 'Penyakit HIV mengakibatkan kondisi tertentu lainnya'),
('B24', 'Unspecified human immunodeficiency virus [HIV] disease', 'Tidak disebutkan human immunodeficiency virus [ HIV ] penyakit'),
('B25.0', 'Cytomegaloviral pneumonitis', 'Pneumonitis Cytomegaloviral'),
('B25.1', 'Cytomegaloviral hepatitis', 'Hepatitis Cytomegaloviral'),
('B25.2', 'Cytomegaloviral pancreatitis', 'Pankreatitis Cytomegaloviral'),
('B25.8', 'Other cytomegaloviral diseases', 'Penyakit cytomegaloviral lainnya'),
('B25.9', 'Cytomegaloviral disease, unspecified', 'Penyakit Cytomegaloviral , tidak spesifik'),
('B26.0', 'Mumps orchitis', 'Gondok orchitis'),
('B26.1', 'Mumps meningitis', 'Gondok meningitis'),
('B26.2', 'Mumps encephalitis', 'Gondok ensefalitis'),
('B26.3', 'Mumps pancreatitis', 'Gondok pankreatitis'),
('B26.8', 'Mumps with other complications', 'Gondok dengan komplikasi lain'),
('B26.9', 'Mumps without complication', 'Gondok tanpa komplikasi'),
('B27.0', 'Gammaherpesviral mononucleosis', 'Mononukleosis Gammaherpesviral'),
('B27.1', 'Cytomegaloviral mononucleosis', 'Mononukleosis Cytomegaloviral'),
('B27.8', 'Other infectious mononucleosis', 'Mononukleosis menular lainnya'),
('B27.9', 'Infectious mononucleosis, unspecified', 'Infeksi mononucleosis , tidak spesifik'),
('B30.0', 'Keratoconjunctivitis due to adenovirus', 'Keratokonjungtivitis karena adenovirus'),
('B30.1', 'Conjunctivitis due to adenovirus', 'Konjungtivitis karena adenovirus'),
('B30.2', 'Viral pharyngoconjunctivitis', 'Viral pharyngoconjunctivitis'),
('B30.3', 'Acute epidemic haemorrhagic conjunctivitis (enteroviral)', 'Epidemi akut hemoragik konjungtivitis ( enterovirus )'),
('B30.8', 'Other viral conjunctivitis', 'Konjungtivitis virus lainnya'),
('B30.9', 'Viral conjunctivitis, unspecified', 'Viral conjunctivitis , tidak spesifik'),
('B33.0', 'Epidemic myalgia', 'Epidemi mialgia'),
('B33.1', 'Ross River disease', 'Penyakit Ross River'),
('B33.2', 'Viral carditis', 'Viral karditis'),
('B33.3', 'Retrovirus infections, not elsewhere classified', 'Infeksi retrovirus , tidak diklasifikasikan di tempat lain'),
('B33.8', 'Other specified viral diseases', 'Penyakit virus lainnya yang spesifik'),
('B34.0', 'Adenovirus infection, unspecified', 'Infeksi adenovirus , tidak spesifik'),
('B34.1', 'Enterovirus infection, unspecified', 'Infeksi enterovirus , tidak spesifik'),
('B34.2', 'Coronavirus infection, unspecified', 'Infeksi coronavirus , tidak spesifik'),
('B34.3', 'Parvovirus infection, unspecified', 'Infeksi Parvovirus , tidak spesifik'),
('B34.4', 'Papovavirus infection, unspecified', 'Infeksi Papovavirus , tidak spesifik'),
('B34.8', 'Other viral infections of unspecified site', 'Infeksi virus lainnya situs yang tidak spesifik'),
('B34.9', 'Viral infection, unspecified', 'Infeksi virus , tidak spesifik'),
('B35.0', 'Tinea barbae and tinea capitis', 'Tinea barbae dan tinea capitis'),
('B35.1', 'Tinea unguium', 'Tinea unguium'),
('B35.2', 'Tinea manuum', 'Tinea manuum'),
('B35.3', 'Tinea pedis', 'Tinea pedis'),
('B35.4', 'Tinea corporis', 'Tinea corporis'),
('B35.5', 'Tinea imbricata', 'Tinea imbricata'),
('B35.6', 'Tinea cruris', 'Tinea cruris'),
('B35.8', 'Other dermatophytoses', 'Dermatophytoses lain'),
('B35.9', 'Dermatophytosis, unspecified', 'Dermatofitosis , tidak spesifik'),
('B36.0', 'Pityriasis versicolor', 'Pityriasis versicolor'),
('B36.1', 'Tinea nigra', 'Tinea nigra'),
('B36.2', 'White piedra', 'Piedra putih'),
('B36.3', 'Black piedra', 'Piedra hitam'),
('B36.8', 'Other specified superficial mycoses', 'Mikosis superfisial lainnya yang spesifik'),
('B36.9', 'Superficial mycosis, unspecified', 'Mikosis Superficial , tidak spesifik'),
('B37.0', 'Candidal stomatitis', 'Candida stomatitis'),
('B37.1', 'Pulmonary candidiasis', 'Kandidiasis paru'),
('B37.2', 'Candidiasis of skin and nail', 'Kandidiasis kulit dan kuku'),
('B37.3', 'Candidiasis of vulva and vagina', 'Kandidiasis dari vulva dan vagina'),
('B37.4', 'Candidiasis of other urogenital sites', 'Kandidiasis situs urogenital lainnya'),
('B37.5', 'Candidal meningitis', 'Meningitis candida'),
('B37.6', 'Candidal endocarditis', 'Endokarditis candida'),
('B37.7', 'Candidal septicaemia', 'Septicemia candida'),
('B37.8', 'Candidiasis of other sites', 'Kandidiasis situs lain'),
('B37.9', 'Candidiasis, unspecified', 'Candidiasis , tidak spesifik'),
('B38.0', 'Acute pulmonary coccidioidomycosis', 'Coccidioidomycosis paru akut'),
('B38.1', 'Chronic pulmonary coccidioidomycosis', 'Coccidioidomycosis paru kronis'),
('B38.2', 'Pulmonary coccidioidomycosis, unspecified', 'Coccidioidomycosis paru , tidak spesifik'),
('B38.3', 'Cutaneous coccidioidomycosis', 'Coccidioidomycosis Cutaneous'),
('B38.4', 'Coccidioidomycosis meningitis', 'Coccidioidomycosis meningitis'),
('B38.7', 'Disseminated coccidioidomycosis', 'Diseminata coccidioidomycosis'),
('B38.8', 'Other forms of coccidioidomycosis', 'Bentuk lain dari coccidioidomycosis'),
('B38.9', 'Coccidioidomycosis, unspecified', 'Coccidioidomycosis , tidak spesifik'),
('B39.0', 'Acute pulmonary histoplasmosis capsulati', 'Akut histoplasmosis paru capsulati'),
('B39.1', 'Chronic pulmonary histoplasmosis capsulati', 'Kronis paru histoplasmosis capsulati'),
('B39.2', 'Pulmonary histoplasmosis capsulati, unspecified', 'Capsulati histoplasmosis paru , tidak spesifik'),
('B39.3', 'Disseminated histoplasmosis capsulati', 'Disebarluaskan capsulati histoplasmosis'),
('B39.4', 'Histoplasmosis capsulati, unspecified', 'Capsulati histoplasmosis , tidak spesifik'),
('B39.5', 'Histoplasmosis duboisii', 'Histoplasmosis duboisii'),
('B39.9', 'Histoplasmosis, unspecified', 'Histoplasmosis , tidak spesifik'),
('B40.0', 'Acute pulmonary blastomycosis', 'Blastomycosis paru akut'),
('B40.1', 'Chronic pulmonary blastomycosis', 'Blastomycosis paru kronis'),
('B40.2', 'Pulmonary blastomycosis, unspecified', 'Blastomycosis paru , tidak spesifik'),
('B40.3', 'Cutaneous blastomycosis', 'Blastomycosis Cutaneous'),
('B40.7', 'Disseminated blastomycosis', 'Diseminata blastomycosis'),
('B40.8', 'Other forms of blastomycosis', 'Bentuk lain dari blastomycosis'),
('B40.9', 'Blastomycosis, unspecified', 'Blastomycosis , tidak spesifik'),
('B41.0', 'Pulmonary paracoccidioidomycosis', 'Paracoccidioidomycosis paru'),
('B41.7', 'Disseminated paracoccidioidomycosis', 'Diseminata paracoccidioidomycosis'),
('B41.8', 'Other forms of paracoccidioidomycosis', 'Bentuk lain dari paracoccidioidomycosis'),
('B41.9', 'Paracoccidioidomycosis, unspecified', 'Paracoccidioidomycosis , tidak spesifik'),
('B42.0', 'Pulmonary sporotrichosis', 'Sporotrichosis paru'),
('B42.1', 'Lymphocutaneous sporotrichosis', 'Sporotrichosis Lymphocutaneous'),
('B42.7', 'Disseminated sporotrichosis', 'Diseminata sporotrichosis'),
('B42.8', 'Other forms of sporotrichosis', 'Bentuk lain dari sporotrichosis'),
('B42.9', 'Sporotrichosis, unspecified', 'Sporotrichosis , tidak spesifik'),
('B43.0', 'Cutaneous chromomycosis', 'Chromomycosis Cutaneous'),
('B43.1', 'Phaeomycotic brain abscess', 'Abses otak Phaeomycotic'),
('B43.2', 'Subcutaneous phaeomycotic abscess and cyst', 'Subkutan phaeomycotic abses dan kista'),
('B43.8', 'Other forms of chromomycosis', 'Bentuk lain dari chromomycosis'),
('B43.9', 'Chromomycosis, unspecified', 'Chromomycosis , tidak spesifik'),
('B44.0', 'Invasive pulmonary aspergillosis', 'Aspergillosis paru invasif'),
('B44.1', 'Other pulmonary aspergillosis', 'Aspergillosis paru lainnya'),
('B44.2', 'Tonsillar aspergillosis', 'Aspergillosis tonsil'),
('B44.7', 'Disseminated aspergillosis', 'Diseminata aspergillosis'),
('B44.8', 'Other forms of aspergillosis', 'Bentuk lain dari aspergillosis'),
('B44.9', 'Aspergillosis, unspecified', 'Aspergillosis , tidak spesifik'),
('B45.0', 'Pulmonary cryptococcosis', 'Kriptokokosis paru'),
('B45.1', 'Cerebral cryptococcosis', 'Kriptokokosis cerebral'),
('B45.2', 'Cutaneous cryptococcosis', 'Kriptokokosis Cutaneous'),
('B45.3', 'Osseous cryptococcosis', 'Kriptokokosis osseus'),
('B45.7', 'Disseminated cryptococcosis', 'Kriptokokosis disebarluaskan '),
('B45.8', 'Other forms of cryptococcosis', 'Bentuk lain dari kriptokokosis'),
('B45.9', 'Cryptococcosis, unspecified', 'Kriptokokosis, tidak spesifik'),
('B46.0', 'Pulmonary mucormycosis', 'Mucormycosis paru'),
('B46.1', 'Rhinocerebral mucormycosis', 'Rhinocerebral mucormycosis'),
('B46.2', 'Gastrointestinal mucormycosis', 'Mucormycosis gastrointestinal'),
('B46.3', 'Cutaneous mucormycosis', 'Mucormycosis Cutaneous'),
('B46.4', 'Disseminated mucormycosis', 'Diseminata mucormycosis'),
('B46.5', 'Mucormycosis, unspecified', 'Mucormycosis , tidak spesifik'),
('B46.8', 'Other zygomycoses', 'Zygomycoses lain'),
('B46.9', 'Zygomycosis, unspecified', 'Zygomycosis , tidak spesifik'),
('B47.0', 'Eumycetoma', 'Eumycetoma'),
('B47.1', 'Actinomycetoma', 'Actinomycetoma'),
('B47.9', 'Mycetoma, unspecified', 'Misetoma , tidak spesifik'),
('B48.0', 'Lobomycosis', 'Lobomycosis'),
('B48.1', 'Rhinosporidiosis', 'Rhinosporidiosis'),
('B48.2', 'Allescheriasis', 'Allescheriasis'),
('B48.3', 'Geotrichosis', 'Geotrichosis'),
('B48.4', 'Penicillosis', 'Penicillosis'),
('B48.7', 'Opportunistic mycoses', 'Mikosis oportunistik'),
('B48.8', 'Other specified mycoses', 'Mikosis tertentu lainnya'),
('B49', 'Unspecified mycosis', 'Mikosis Tidak spesifik'),
('B50.0', 'Plasmodium falciparum malaria with cerebral complications', 'Malaria Plasmodium falciparum dengan komplikasi serebral'),
('B50.8', 'Other severe and complicated Plasmodium falciparum malaria', 'Malaria Plasmodium falciparum berat dan rumit lainnya'),
('B50.9', 'Plasmodium falciparum malaria, unspecified', 'Malaria plasmodium falciparum , tidak spesifik'),
('B51.0', 'Plasmodium vivax malaria with rupture of spleen', 'Malaria plasmodium vivax dengan pecahnya limpa');