-- PostgreSQL converted from MySQL dump
-- Original: b_ms_diagnosa
-- Rows limited to 100

create table "b_ms_diagnosa" (
	"id" bigint,
	"kode" varchar(45),
	"nama" varchar(750),
	"level" smallint,
	"parent_id" bigint,
	"parent_kode" varchar(45),
	"surveilance" smallint,
	"islast" smallint,
	"aktif" smallint,
	"dg_kode" varchar(30),
	"resume_ri" smallint,
	"resume_rj" smallint,
	"resume_cd" smallint,
	"tahun" smallint,
	"kodeina" varchar(45)
);

insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22760','A00','Cholera','1','0','','1','0','0','001','0','0','0','2008','A00');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22761','A00.0','Cholera due to Vibrio cholerae 01, biovar cholerae','2','22760','A00','1','1','0','001','0','0','0','2008','A00.0');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22762','A00.1','Cholera due to Vibrio cholerae 01, biovar eltor','2','22760','A00','1','1','0','001','0','0','0','2008','A00.1');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22763','A00.9','Cholera, unspecified','2','22760','A00','1','1','0','001','0','0','0','2008','A00.9');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22764','A01','Typhoid and paratyphoid fevers','1','0','','1','0','0','002','0','0','0','2008','A01');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22765','A01.0','Typhoid fever','2','22764','A01','1','1','0','002','0','0','0','2008','A01.0');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22766','A01.1','Paratyphoid fever A','2','22764','A01','1','1','0','002','0','0','0','2008','A01.1');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22767','A01.2','Paratyphoid fever B','2','22764','A01','1','1','0','002','0','0','0','2008','A01.2');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22768','A01.3','Paratyphoid fever C','2','22764','A01','1','1','0','002','0','0','0','2008','A01.3');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22769','A01.4','Paratyphoid fever, unspecified','2','22764','A01','1','1','0','002','0','0','0','2008','A01.4');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22770','A02','Other salmonella infections','1','0','','0','0','0','006','0','0','0','2008','A02');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22771','A02.0','Salmonella enteritis','2','22770','A02','0','1','0','006','0','0','0','2008','A02.0');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22772','A02.1','Salmonella septicaemia','2','22770','A02','0','1','0','006','0','0','0','2008','A02.1');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22773','A02.2+','Localized salmonella infections','2','22770','A02','0','1','0','006','0','0','0','2008','A02.2+');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22774','A02.8','Other specified salmonella infections','2','22770','A02','0','1','0','006','0','0','0','2008','A02.8');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22775','A02.9','Salmonella infection, unspecified','2','22770','A02','0','1','0','006','0','0','0','2008','A02.9');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22776','A03','Shigellosis','1','0','','0','0','0','003','0','0','0','2008','A03');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22777','A03.0','Shigellosis due to Shigella dysenteriae','2','22776','A03','0','1','0','003','0','0','0','2008','A03.0');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22778','A03.1','Shigellosis due to Shigella flexneri','2','22776','A03','0','1','0','003','0','0','0','2008','A03.1');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22779','A03.2','Shigellosis due to Shigella boydii','2','22776','A03','0','1','0','003','0','0','0','2008','A03.2');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22780','A03.3','Shigellosis due to Shigella sonnei','2','22776','A03','0','1','0','003','0','0','0','2008','A03.3');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22781','A03.8','Other shigellosis','2','22776','A03','0','1','0','003','0','0','0','2008','A03.8');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22782','A03.9','Shigellosis, unspecified','2','22776','A03','0','1','0','003','0','0','0','2008','A03.9');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22783','A04','Other bacterial intestinal infections','1','0','','0','0','0','006','0','0','0','2008','A04');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22784','A04.0','Enteropathogenic Escherichia coli infection','2','22783','A04','0','1','0','006','0','0','0','2008','A04.0');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22785','A04.1','Enterotoxigenic Escherichia coli infection','2','22783','A04','0','1','0','006','0','0','0','2008','A04.1');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22786','A04.2','Enteroinvasive Escherichia coli infection','2','22783','A04','0','1','0','006','0','0','0','2008','A04.2');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22787','A04.3','Enterohaemorrhagic Escherichia coli infection','2','22783','A04','0','1','0','006','0','0','0','2008','A04.3');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22788','A04.4','Other intestinal Escherichia coli infections','2','22783','A04','0','1','0','006','0','0','0','2008','A04.4');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22789','A04.5','Campylobacter enteritis','2','22783','A04','0','1','0','006','0','0','0','2008','A04.5');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22790','A04.6','Enteritis due to Yersinia enterocolitica','2','22783','A04','0','1','0','006','0','0','0','2008','A04.6');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22791','A04.7','Enterocolitis due to Clostridium difficile','2','22783','A04','0','1','0','006','0','0','0','2008','A04.7');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22792','A04.8','Other specified bacterial intestinal infections','2','22783','A04','0','1','0','006','0','0','0','2008','A04.8');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22793','A04.9','Bacterial intestinal infection, unspecified','2','22783','A04','0','1','0','006','0','0','0','2008','A04.9');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22794','A05','Other bacterial foodborne intoxications','1','0','','0','0','0','006','0','0','0','2008','A05');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22795','A05.0','Foodborne staphylococcal intoxication','2','22794','A05','0','1','0','006','0','0','0','2008','A05.0');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22796','A05.1','Botulism','2','22794','A05','0','1','0','006','0','0','0','2008','A05.1');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22797','A05.2','Foodborne Clostridium perfringens [Clostridium welchii] intoxication','2','22794','A05','0','1','0','006','0','0','0','2008','A05.2');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22798','A05.3','Foodborne Vibrio parahaemolyticus intoxication','2','22794','A05','0','1','0','006','0','0','0','2008','A05.3');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22799','A05.4','Foodborne Bacillus cereus intoxication','2','22794','A05','0','1','0','006','0','0','0','2008','A05.4');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22800','A05.8','Other specified bacterial foodborne intoxications','2','22794','A05','0','1','0','006','0','0','0','2008','A05.8');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22801','A05.9','Bacterial foodborne intoxication, unspecified','2','22794','A05','0','1','0','006','0','0','0','2008','A05.9');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22802','A06','Amoebiasis','1','0','','0','0','0',NULL,'0','0','0','2008','A06');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22803','A06.0','Acute amoebic dysentery','2','22802','A06','0','1','0','004.9','0','0','0','2008','A06.0');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22804','A06.1','Chronic intestinal amoebiasis','2','22802','A06','0','1','0',NULL,'0','0','0','2008','A06.1');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22805','A06.2','Amoebic nondysenteric colitis','2','22802','A06','0','1','0',NULL,'0','0','0','2008','A06.2');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22806','A06.3','Amoeboma of intestine','2','22802','A06','0','1','0','004.9','0','0','0','2008','A06.3');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22807','A06.4','Amoebic liver abscess','2','22802','A06','0','1','0','004.0','0','0','0','2008','A06.4');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22808','A06.5 ','Amoebic lung abscess (J99.8)','2','22802','A06','0','1','0','004.9','0','0','0','2008','A06.5+');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22809','A06.6 ','Amoebic brain abscess (G07)','2','22802','A06','0','1','0','004.9','0','0','0','2008','A06.6+');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22810','A06.7','Cutaneous amoebiasis','2','22802','A06','0','1','0','004.9','0','0','0','2008','A06.7');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22811','A06.8','Amoebic infection of other sites','2','22802','A06','0','1','0','004.9','0','0','0','2008','A06.8');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22812','A06.9','Amoebiasis, unspecified','2','22802','A06','0','1','0','004.9','0','0','0','2008','A06.9');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22813','A07','Other protozoal intestinal diseases','1','0','','0','0','0','006','0','0','0','2008','A07');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22814','A07.0','Balantidiasis','2','22813','A07','0','1','0','006','0','0','0','2008','A07.0');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22815','A07.1','Giardiasis [lambliasis]','2','22813','A07','0','1','0','006','0','0','0','2008','A07.1');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22816','A07.2','Cryptosporidiosis','2','22813','A07','0','1','0','006','0','0','0','2008','A07.2');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22817','A07.3','Isosporiasis','2','22813','A07','0','1','0','006','0','0','0','2008','A07.3');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22818','A07.8','Other specified protozoal intestinal diseases','2','22813','A07','0','1','0','006','0','0','0','2008','A07.8');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22819','A07.9','Protozoal intestinal disease, unspecified','2','22813','A07','0','1','0','006','0','0','0','2008','A07.9');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22820','A08','Viral and other specified intestinal infections','1','0','','0','0','0','006','0','0','0','2008','A08');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22821','A08.0','Rotaviral enteritis','2','22820','A08','0','1','0','006','0','0','0','2008','A08.0');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22822','A08.1','Acute gastroenteropathy due to Norwalk agent','2','22820','A08','0','1','0','006','0','0','0','2008','A08.1');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22823','A08.2','Adenoviral enteritis','2','22820','A08','0','1','0','006','0','0','0','2008','A08.2');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22824','A08.3','Other viral enteritis','2','22820','A08','0','1','0','006','0','0','0','2008','A08.3');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22825','A08.4','Viral intestinal infection, unspecified','2','22820','A08','0','1','0','006','0','0','0','2008','A08.4');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22826','A08.5','Other specified intestinal infections','2','22820','A08','0','1','0','006','0','0','0','2008','A08.5');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22827','A09','Diarrhoea and gastroenteritis of presumed infectious origin','1','0','','1','0','0','','0','0','0','2008','A09');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22828','A09.0','Other and unspecified gastroenteritis of infectious origin','2','22827','A09','1','1','0','005','0','0','0','2008','A09.0');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22829','A09.9','Gastroenteritis and colitis of unspecified origin','2','22827','A09','1','1','0','005','0','0','0','2008','A09.9');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22830','A15','Respiratory tuberculosis, bacteriologically and histologically confirmed','1','0','','1','0','0',NULL,'0','1','1','2008','A15');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22831','A15.0','Tuberculosis of lung, confirmed by sputum microscopy with or without culture','2','22830','A15','1','1','0','007.0','0','1','1','2008','A15.0');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22832','A15.1','Tuberculosis of lung, confirmed by culture only','2','22830','A15','1','1','0','007.1','0','1','1','2008','A15.1');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22833','A15.2','Tuberculosis of lung, confirmed histologically','2','22830','A15','1','1','0','007.1','0','1','1','2008','A15.2');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22834','A15.3','Tuberculosis of lung, confirmed by unspecified means','2','22830','A15','1','1','0','007.1','0','1','1','2008','A15.3');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22835','A15.4','Tuberculosis of intrathoracic lymph nodes, confirmed bacteriologically and histologically','2','22830','A15','1','1','0','007.1','0','1','1','2008','A15.4');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22836','A15.5','Tuberculosis of larynx, trachea and bronchus, confirmed bacteriologically and histologically','2','22830','A15','1','1','0','007.1','0','1','1','2008','A15.5');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22837','A15.6','Tuberculous pleurisy, confirmed bacteriologically and histologically','2','22830','A15','1','1','0','007.1','0','1','1','2008','A15.6');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22838','A15.7','Primary respiratory tuberculosis, confirmed bacteriologically and histologically','2','22830','A15','1','1','0','007.1','0','1','1','2008','A15.7');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22839','A15.8','Other respiratory tuberculosis, confirmed bacteriologically and histologically','2','22830','A15','1','1','0','007.1','0','1','1','2008','A15.8');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22840','A15.9','Respiratory tuberculosis unspecified, confirmed bacteriologically and histologically','2','22830','A15','1','1','0','007.1','0','1','1','2008','A15.9');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22841','A16','Respiratory tuberculosis, not confirmed bacteriologically or histologically','1','0','','0','0','0',NULL,'0','1','1','2008','A16');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22842','A16.0','Tuberculosis of lung, bacteriologically and histologically negative','2','22841','A16','0','1','0','007.1','0','1','1','2008','A16.0');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22843','A16.1','Tuberculosis of lung, bacteriological and histological examination not done','2','22841','A16','0','1','0','007.1','0','1','1','2008','A16.1');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22844','A16.2','Tuberculosis of lung, without mention of bacteriological or histological confirmation','2','22841','A16','0','1','0','007.1','0','1','1','2008','A16.2');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22845','A16.3','Tuberculosis of intrathoracic lymph nodes, without mention of bacteriological or histological confirmation','2','22841','A16','0','1','0','007.9','0','1','1','2008','A16.3');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22846','A16.4','Tuberculosis of larynx, trachea and bronchus, without mention of bacteriological or histological confirmation','2','22841','A16','0','1','0','007.9','0','1','1','2008','A16.4');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22847','A16.5','Tuberculous pleurisy, without mention of bacteriological or histological confirmation','2','22841','A16','0','1','0','007.9','0','1','1','2008','A16.5');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22848','A16.7','Primary respiratory tuberculosis without mention of bacteriological or histological confirmation','2','22841','A16','0','1','0','007.9','0','1','1','2008','A16.7');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22849','A16.8','Other respiratory tuberculosis, without mention of bacteriological or histological confirmation','2','22841','A16','0','1','0','007.9','0','1','1','2008','A16.8');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22850','A16.9','Respiratory tuberculosis unspecified, without mention of bacteriological or histological confirmation','2','22841','A16','0','1','0','007.9','0','1','1','2008','A16.9');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22851','A17+','Tuberculosis of nervous system','1','0','','0','0','0',NULL,'0','1','1','2008','A17+');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22852','A17.0 ','Tuberculous meningitis (G01)','2','22851','A17','0','1','0','008.0','0','1','1','2008','A17.0+');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22853','A17.1 ','Meningeal tuberculoma (G07)','2','22851','A17','0','1','0','008.1','0','1','1','2008','A17.1+');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22854','A17.8+','Other tuberculosis of nervous system','2','22851','A17','0','1','0','008.1','0','1','1','2008','A17.8+');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22855','A17.9 ','Tuberculosis of nervous system, unspecified (G99.8)','2','22851','A17','0','1','0','008.1','0','1','1','2008','A17.9+');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22856','A18','Tuberculosis of other organs','1','0','','0','0','0',NULL,'0','1','1','2008','A18');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22857','A18.0+','Tuberculosis of bones and joints','2','22856','A18','0','1','0','008.2','0','1','1','2008','A18.0+');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22858','A18.1+','Tuberculosis of genitourinary system','2','22856','A18','0','1','0','008.9','0','1','1','2008','A18.1+');
insert into "b_ms_diagnosa" ("id", "kode", "nama", "level", "parent_id", "parent_kode", "surveilance", "islast", "aktif", "dg_kode", "resume_ri", "resume_rj", "resume_cd", "tahun", "kodeina") values('22859','A18.2','Tuberculous peripheral lymphadenopathy','2','22856','A18','0','1','0','008.3','0','1','1','2008','A18.2');